# Generated by Django 5.2.5 on 2025-08-31 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_shops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopcustomer',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_shops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopcustomer',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_customers', to='shops.shop'),
        ),
        migrations.AlterUniqueTogether(
            name='shop',
            unique_together={('owner', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='shopcustomer',
            unique_together={('shop', 'customer')},
        ),
    ]
