name: CI/CD Pipeline for Render

# Trigger workflow on push and merge events to the main branch
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy and Notify
    runs-on: ubuntu-latest
    steps:
      # 1. Get the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Set up Python and install dependencies
      - name: Setup Python and Install Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
      - run: pip install -r requirements.txt

      # 3. Deploy to Render by calling the deploy hook
      - name: Deploy to Render
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"

      # 4. Send a success notification to Google Chat
      - name: Send Success Notification
        if: success()
        uses: Asankah/google-chat-action@v1.3.1 # <-- UPDATED ACTION
        with:
          webhookUrl: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }} # <-- UPDATED PARAMETER NAME
          card: | # <-- UPDATED PARAMETER NAME
            {
              "cardsV2": [{
                "cardId": "deploy-success",
                "card": {
                  "header": { "title": "✅ Deployment Successful" },
                  "sections": [{
                    "widgets": [
                      { "textParagraph": { "text": "<b>Repo:</b> ${{ github.repository }}<br><b>Commit:</b> <i>${{ github.event.head_commit.message }}</i>" } },
                      { "buttonList": { "buttons": [{ "text": "View Workflow", "onClick": { "openLink": { "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" } } }] } }
                    ]
                  }]
                }
              }]
            }

      # 5. Send a failure notification to Google Chat
      - name: Send Failure Notification
        if: failure()
        uses: Asankah/google-chat-action@v1.3.1 # <-- UPDATED ACTION
        with:
          webhookUrl: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }} # <-- UPDATED PARAMETER NAME
          card: | # <-- UPDATED PARAMETER NAME
            {
              "cardsV2": [{
                "cardId": "deploy-failure",
                "card": {
                  "header": { "title": "❌ Deployment Failed" },
                  "sections": [{
                    "widgets": [
                      { "textParagraph": { "text": "The workflow for <b>${{ github.repository }}</b> failed. Check the logs for details." } },
                      { "buttonList": { "buttons": [{ "text": "View Workflow", "onClick": { "openLink": { "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" } } }] } }
                    ]
                  }]
                }
              }]
            }
